name: darb
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # المكتبات الأساسية
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  http: ^1.2.0
  http_parser: ^4.1.0
  image_picker: ^1.1.2
  intl: 0.20.2
  pinput: ^6.0.2
  flutter_svg: ^2.0.7
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.0
  qr_flutter: ^4.1.0

  # مكتبات Firebase (إصدارات متوافقة)
  firebase_core: ^4.11.0
  firebase_analytics: ^12.4.3
  firebase_messaging: ^16.4.0
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.jpg
    - assets/lang/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700